//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: LLMaskModel.kt:7</p>
  /// </summary>
  [JetBrains.Application.ShellComponent(Application.Parts.Instantiation.DemandAnyThreadSafe)]
  public class LLMaskModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<string, string> ObfuscateFile => _ObfuscateFile;
    
    //private fields
    [NotNull] private readonly RdCall<string, string> _ObfuscateFile;
    
    //primary constructor
    private LLMaskModel(
      [NotNull] RdCall<string, string> obfuscateFile
    )
    {
      if (obfuscateFile == null) throw new ArgumentNullException("obfuscateFile");
      
      _ObfuscateFile = obfuscateFile;
      BindableChildren.Add(new KeyValuePair<string, object>("obfuscateFile", _ObfuscateFile));
    }
    //secondary constructor
    private LLMaskModel (
    ) : this (
      new RdCall<string, string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -5166291633154748389L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    public LLMaskModel(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("LLMaskModel"));
      this.BindTopLevel(lifetime, protocol, "LLMaskModel");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("LLMaskModel (");
      using (printer.IndentCookie()) {
        printer.Print("obfuscateFile = "); _ObfuscateFile.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
